# Generated by Django 2.2 on 2019-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_auto_20190402_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_people',
            name='full_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='wonder_archive_people',
            name='illustration',
            field=models.CharField(default='神秘生物，暂无说明', max_length=200),
        ),
        migrations.AddField(
            model_name='wonder_archive_people',
            name='image',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='wonder_archive_people',
            name='position',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='wonder_archive_people',
            name='whether_user',
            field=models.IntegerField(default=0),
        ),
    ]
