# Generated by Django 2.2 on 2019-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0003_auto_20190402_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='full_name',
            field=models.CharField(default='官方名字未知', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='name',
            field=models.CharField(default='这人很严肃，没有nickname', max_length=200),
        ),
    ]
