# Generated by Django 2.2 on 2019-04-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0004_auto_20190402_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wonder_archive_gt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wonder_archive_gt',
            name='text',
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='illustration',
            field=models.CharField(default='具体内容无可奉告', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='main_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Wonder_Archive_People'),
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='story_file_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Story_File_Status'),
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='tag1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='tag2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='tag3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wonder_archive_gt',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
