# Generated by Django 2.2 on 2019-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0006_auto_20190406_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_file_status',
            name='date',
            field=models.CharField(default='未知日期', max_length=50),
        ),
    ]
