# Generated by Django 2.2 on 2019-04-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0008_chat_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='name',
            field=models.CharField(default='这人很严肃，没有nickname', max_length=50),
        ),
    ]
