# Generated by Django 2.2 on 2019-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0009_auto_20190408_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_people',
            name='nick_name',
            field=models.CharField(default='这人很严肃，没有nickname', max_length=50),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
