# Generated by Django 2.2 on 2019-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0011_wonder_archive_people_active_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_gt',
            name='active_state',
            field=models.IntegerField(default=0),
        ),
    ]
