# Generated by Django 2.2 on 2019-04-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0012_wonder_archive_gt_active_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_log',
            name='active_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat_log',
            name='content',
            field=models.CharField(default='', max_length=600),
        ),
    ]
