# Generated by Django 2.2 on 2019-05-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0013_auto_20190418_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story_file_status',
            old_name='last_figure_url',
            new_name='last_figure_center_url',
        ),
        migrations.AddField(
            model_name='story_file_status',
            name='last_figure_left_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='story_file_status',
            name='last_figure_right_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
