# Generated by Django 2.2 on 2019-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0014_auto_20190504_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_people',
            name='avatar',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
