# Generated by Django 2.2 on 2019-05-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0015_wonder_archive_people_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_people',
            name='background',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
