# Generated by Django 2.2 on 2019-05-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0016_wonder_archive_people_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_state', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('rank', models.CharField(default=' ', max_length=5)),
                ('title', models.CharField(default=' ', max_length=50)),
                ('illustration', models.CharField(default=' ', max_length=200)),
                ('figure', models.CharField(default=' ', max_length=200)),
                ('background', models.CharField(default=' ', max_length=200)),
                ('story_file_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Story_File_Status')),
            ],
        ),
    ]
