# Generated by Django 2.2 on 2019-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0017_store_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_card',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
