# Generated by Django 2.2 on 2019-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0019_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
