# Generated by Django 2.2 on 2019-05-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0021_auto_20190512_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='pro_type',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
