# Generated by Django 2.2 on 2019-05-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0022_shopping_cart_pro_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Story_File_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('value', models.IntegerField(default=2)),
                ('title', models.CharField(default='', max_length=50)),
                ('story_file_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.Story_File_Status')),
            ],
        ),
    ]
