# Generated by Django 2.2 on 2019-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0023_daily_story_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_story_file_status',
            name='month',
            field=models.CharField(default='', max_length=50),
        ),
    ]
