# Generated by Django 2.2 on 2019-05-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0024_daily_story_file_status_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_story_file_status',
            name='story_file_status',
        ),
    ]
