# Generated by Django 2.2 on 2019-05-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0025_remove_daily_story_file_status_story_file_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_card',
            name='name',
        ),
        migrations.AddField(
            model_name='store_card',
            name='main_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Wonder_Archive_People'),
        ),
    ]
