# Generated by Django 2.2 on 2019-05-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0026_auto_20190513_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder_archive_people',
            name='k',
            field=models.CharField(default='', max_length=30),
        ),
    ]
