# Generated by Django 2.2 on 2019-05-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0028_remove_wonder_archive_people_k'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_interval', models.IntegerField(default=100)),
                ('paragraph_interval', models.IntegerField(default=1000)),
            ],
        ),
    ]
