# Generated by Django 2.2 on 2019-05-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0030_auto_20190514_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_log',
            old_name='active_state',
            new_name='update_state',
        ),
        migrations.AlterField(
            model_name='chat_log',
            name='content',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='avatar',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='background',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='image',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
