# Generated by Django 2.2 on 2019-05-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0033_auto_20190515_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_card',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='store_card',
            name='story_file_status',
        ),
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/00', max_length=200),
        ),
        migrations.CreateModel(
            name='Store_Card_Own',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('store_card', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Store_Card')),
                ('story_file_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Story_File_Status')),
            ],
        ),
    ]
