# Generated by Django 2.2 on 2019-05-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0034_auto_20190516_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_card',
            name='main_person',
        ),
        migrations.AddField(
            model_name='store_card',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='store_card_own',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moment.Wonder_Archive_People'),
        ),
    ]
