# Generated by Django 2.2 on 2019-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0035_auto_20190516_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_card',
            name='active_state',
        ),
        migrations.AddField(
            model_name='store_card_own',
            name='active_state',
            field=models.IntegerField(default=0),
        ),
    ]
