# Generated by Django 2.2 on 2019-05-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0036_auto_20190516_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='chat_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.Wonder_Archive_People'),
        ),
        migrations.AlterField(
            model_name='chat_log',
            name='story_file_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.Story_File_Status'),
        ),
    ]
