# Generated by Django 2.2 on 2019-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0038_auto_20190516_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/11', max_length=200),
        ),
    ]
