# Generated by Django 2.2 on 2019-05-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0040_auto_20190523_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/1', max_length=200),
        ),
    ]
