# Generated by Django 2.2 on 2019-05-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0042_auto_20190524_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/1', max_length=200),
        ),
    ]
