# Generated by Django 2.2 on 2019-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0043_auto_20190525_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/0', max_length=200),
        ),
    ]
