# Generated by Django 2.2 on 2019-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0045_auto_20190602_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='character_interval',
            field=models.IntegerField(default=50),
        ),
    ]
