# Generated by Django 2.2 on 2019-09-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0047_auto_20190603_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_file_status',
            name='file_dir',
            field=models.CharField(default='/static/moment/story/1_eng', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='full_name',
            field=models.CharField(default='Unkown name', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='illustration',
            field=models.CharField(default='Mysterious creature. No intro valid.', max_length=200),
        ),
        migrations.AlterField(
            model_name='wonder_archive_people',
            name='nick_name',
            field=models.CharField(default='Unknown Position', max_length=50),
        ),
    ]
